### ISSUE TITLE
function is not defined :( 

### ISSUE THREAD

**Issue by JoyKrishnaMondal** [substack/webworkify#25] opened 2016-05-22 19:19 UTC
I am having this error while trying to test the module for simple workers. 

![webworker](https://cloud.githubusercontent.com/assets/3383928/15455968/7c891f64-205a-11e6-81b6-5fe08ad5c8e1.png)

hopefully there is a simple solution.

**Comment by anandthakker** [comment] 2016-05-23 11:45
@JoyKrishnaMondal can you include the code you used for the main thread?

**Comment by mourner** [comment] 2016-09-07 15:46
No answer, so closing as not actionable.

**Closed by mourner** 2016-09-07 15:46 UTC

**Comment by naydenov1** [comment] 2017-03-18 15:23
Hi, I am having the same issue.
I call the code from within a function:
`	function start () {
		let w = work(require('./worker.js'));
		w.addEventListener('message', function (ev) {
		    console.info(ev.data);
		});
       }
`
Any idea why is this happening?

**Comment by mourner** [comment] 2017-03-18 15:36
@naydenov1 can you set up a small JSFiddle test case that reproduces the error?

**Comment by naydenov1** [comment] 2017-03-18 16:03
Unfortunately, that is not possible since I require many libraries inside the worker and the function is part of a bigger bundled code. It would be hard to replicate it inside a Fiddle. Perhaps bundling the code  may be the reason?

**Comment by mourner** [comment] 2017-03-18 16:23
You could try reducing your application until the bug stops reproducing to find out the exact culprit, and then create an isolated test case with it only. Without a test case, we'll have no way to diagnose the issue.

**Comment by tikri** [comment] 2017-03-21 13:37
I'm having the same issue right now. I just fixed it for me by changing
`
// try to call default if defined to also support babel esmodule
// exports
'var f = require(' + stringify(wkey) + ');' +
'(f.default ? f.default : f)(self);'
`
to
`
// try to call default if defined to also support babel esmodule
// exports
'var f = require(' + stringify(wkey) + ');' +
'(f)(self);'
`
I really don't know why it breaks, because f.default is undefined and also `console.log(f.default ? "yes" : "no");` outputs "no"...
Sorry that I don't have time to set up a JSFiddle right now. Just some information about our worker: it requires the modules lodash and sax and the whole project is browserified and babelified.

**Comment by mourner** [comment] 2017-03-21 13:42
Hmm, that's really quite surprising. Let us know if you have a test case or more details.

**Comment by tikri** [comment] 2017-03-21 14:12
Found the cause of the problem for me. Just required a plain JS worker and forgot to wrap it in `module.exports = function (self) {...}`. Wondering why it worked at all... Sorry for that :-/
